var V = new Pseudo3D.Math.Vector();
var C = new Pseudo3D.Resources.Color();
var I = new Pseudo3D.Resources.ImageContainer();
var SS = new Pseudo3D.Resources.SpriteSheet();
var CAM = new Pseudo3D.Camera({x: undefined, y: undefined});
var E = new Pseudo3D.Entity();
var R = new Pseudo3D.Ray();
var REN = new Pseudo3D.Renderer();
var SC = new Pseudo3D.Scene();
var S = new Pseudo3D.Sprite({x: undefined, y: undefined});
console.log(V,C,I,SS,CAM,E,R,REN,SC,S);